### ISSUE TITLE
Handle time synchronization problem robustly

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#20]
When using IAM authentication, the time on the server hosting FutureGateway must be correct. Both parties (FG and IAM) pass timestamped messages and lack of synchronization causes in the end the "message ahead of time" condition.

Currently, the problem is not handled very well. User trying to log in via IAM is suddenly presented with browser's general "something went wrong" page without any explanation. However, on the backend side, there is a thrown exception: ``com.nimbusds.jwt.proc.BadJWTException: JWT issue time ahead of current time``. This exception should be caught and handled in a user-friendly way, because non-admin cannot see the logs and will never find out what went wrong.

Additionally, I suggest to add in the documentation, the following one-liner which sets time to the valid value: (run as root)
```bash
# date --set="$(curl -I https://iam-test.indigo-datacloud.eu | grep Date | awk '{$1 = ""; print}')"
```

**Comment by fmarco76** [comment]
We can manage the exception but I do not think it is a good message for
the end user. It is a configuration problem for him. Maybe, we can send
a message to the administrator or I do not know what else.

For the sync, it should be with a time server and each administrator has to configure properly.
All servers accessing the token have to synchronised so it is better if they do independently and
do not depend from the other. We could add in the documentation to keep the time correct.

**Comment by fmarco76** [comment]
I do not think this is a real bug but something we can get better

**Comment by fmarco76** [comment]
Added note in the documentation (see commit: 360ebdc4f4bd2b73af7e9e9e74fd6fe0b45c4a02)
https://indigo-dc.gitbooks.io/liferay-plugins/content/doc/admin.html
