### ISSUE TITLE
Customisable Application Portlet makes REST calls for unlogged user

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#25]
* Component: Customisable Application Portlet
* Version: v2.0.3
* Steps to reproduce:
  1. Visit http://fgw02.ncg.ingrid.pt/ (or other place where LiferayPlugins are installed)
* Actual behaviour: a browser window appears with message "401"; in the developer console, one may see that the portlet makes unauthorized REST calls
* Expected behaviour: nothing happens until ther user logs in

**Comment by fmarco76** [comment]
The portlet should not be visible to users before they log-in. In Liferay it is possible to block the page or each portlet. Look at https://sgw-test.ct.infn.it/web/guest/testportlets. In  this case the portlet is blocked if the user is not authenticate.

Nevertheless, a check on the availability of the token has been included so the message will not appear (see commit b7cb01c38635b101977587857c6ac89de07b9228).
