### ISSUE TITLE
Improve error handling in Customisable Application Portlet

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#26]
* Component: Customisable Application Portlet
* Version: v2.0.3
* Steps to reproduce
  1. Open http://fgw02.ncg.ingrid.pt
  2. Sign in
  3. Select "..." -> "Configure" on the component
  4. Select any application
  5. Click on "Interface configuration JSON" -> "new json"
  6. Copy-paste a lorem ipsum paragraph
* Actual behaviour: Message: "You have successfully updated the setup", but nothing happens to the portlet
* Expected behaviour: JSON configuration is properly validated. If the error is more subtle i.e. the user input is a real JSON but with a minor mistake, then the error message should inform user about that.

**Comment by fmarco76** [comment]
Added a check on json syntax. If the json is not valid an alert window with the error raises and the value is not stored. No checks on values are performed (see commit c516bb332ac7e87ee3776a52894b8fc310d23011)
