### ISSUE TITLE
Misleading errors in log file about problems parsing a valid token 

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#27]
* Component: IAM integration plugin
* Version: v2.0.3
* Actual behaviour: The log file is full of messages like below. But the token which is logged can be verified (e.g. on https://jwt.io/) to be perfectly parsable:
```
11:35:30,536 ERROR [http-nio-8080-exec-13][IAMImpl:801] The following token cannot be parsed: ...TOKEN...
```
* Expected behaviour: If a token is parsable, there should not be any errors logged about problems parsing it. Probably there is some other reason an exception is thrown, but in the catch block it is incorrectly handled as an unparsable token.

**Comment by fmarco76** [comment]
The error is raised in many circumstances and this is correct but the log is useless. I have moved the log to debug so in production it should not be present (see commit 65d7c97c0d3c254b523826f24d873cf03067ee72).
