### ISSUE TITLE
Support Runtime Data of the tasks

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#28]
* Component: Customisable Application Portlet
* Version: v2.0.3
* Description: Can you add support for Runtime Data? I would like to access (maybe even add/modify) them for tasks submitted via Customisable Application Portlet.

**Comment by fmarco76** [comment]
Fixed with https://github.com/indigo-dc/LiferayPlugIns/commit/e3ebabe1f53b4e0cda9f94c8b9f0be3aac9e4d93
