### ISSUE TITLE
Default values in TOSCA template should be selected in Customisable Application Portlet

### ISSUE THREAD

**Issue by tzok** [indigo-dc/LiferayPlugIns#38]
When the user interface is presented to the user in Customisable Application Portlet, it does not set initial values to the default values from the TOSCA template. This should be changed, because defaults are set so that the new users can just instantiate a VM with TOSCA without changing anything. For example, for DARIAH a node needs to 4 CPUs and it is set so in TOSCA's default. But the portlet sets that to 1 CPU and the instantiated machine is broken without user intervention.

CC: @ddavidovic

**Comment by fmarco76** [comment]
Not reproducible
